### ISSUE TITLE
Error: Cannot find module 'common-tags'

### ISSUE THREAD

**Issue by coogamer352757** [badRyuk/GenBot#1]
when i open terminal and type in node index.js it shows up as
Error: Cannot find module 'common-tags'
Require stack:
- C:\Users\HP\Desktop\GenBot-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\HP\Desktop\GenBot-master\index.js:7:34)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\HP\\Desktop\\GenBot-master\\index.js' ]

**Comment by badRyuk** [comment]
@coogamer352757 
This error occurs if you have a missing module. Make sure you have discord.js and common-tags installed.
Run ``npm install common-tags`` in the terminal
Next just start the bot using ``node index.js``. 

The bot must work as expected now. If this helps you out please close the issue, if not, I'll try to help you out
